### ISSUE TITLE
在mac os上好像无效

### ISSUE THREAD

**Issue by fengyie007** [pengzhile/MyBatisCodeHelper-Pro-Crack#2]
在mac os上好像无效

**Comment by fengyie007** [comment]
idea 2018.3.3安装了release里的MybatisCodeHelperNew-2.0.3-IDEA173-IDEA183.zip 插件。
然后使用该代码库的java代码，运行生成了文件，在/Users/jason/.config/install/setup.dll目录。
打开idea，提示输入激活码，输入任意字符后，提示如下。
![image](https://user-images.githubusercontent.com/241077/51391865-33beb700-1b6e-11e9-8fcd-60f53592724d.png)

![image](https://user-images.githubusercontent.com/241077/51391856-2efa0300-1b6e-11e9-897a-bf90479a237e.png)

**Comment by pengzhile** [comment]
这是你网络问题，连不上作者的激活服务器。

**Comment by fengyie007** [comment]
可以了，多谢
